# Generated by Django 5.2.5 on 2025-09-02 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'IN Progress'), ('done', 'Done')], default='todo', max_length=50)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2025, 9, 2, 11, 14, 30, 489127, tzinfo=datetime.timezone.utc))),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'create_at'], name='task_todo_title_8a7b98_idx'), models.Index(fields=['delete_at'], name='task_todo_delete__212f75_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__lte', 5)), name='priority__range_1_5'), models.CheckConstraint(condition=models.Q(('due_date__gte', datetime.datetime(2025, 9, 2, 11, 14, 30, 489359, tzinfo=datetime.timezone.utc))), name='due_date_gte_today')],
            },
        ),
    ]
