# Generated by Django 5.2.5 on 2025-09-02 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todo',
            name='due_date_gte_today',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 11, 43, 52, 211278, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'IN Progress'), ('done', 'Done'), ('archive', 'Archive')], default='todo', max_length=50),
        ),
    ]
