# Generated by Django 5.2.5 on 2025-09-02 11:51

import django.utils.timezone
import task.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[task.validators.datetime_checker]),
        ),
    ]
